name: CI

on:
  push:
    branches:
    - main
    - bugfix/**
    - feature/**
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.2
      with:
        path: ~/.m2/repository
        key: maven-repo

    - name: Build
      run: mvn -B package

  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Release
      uses: qcastel/github-actions-maven-release@v1.12.27
      with:
        release-branch-name: ${{ github.ref }} 
        access-token: ${{ secrets.GITHUB_TOKEN }}
        maven-options:  "-DpushChanges=false -DautoVersionSubmodules=true"
        maven-args: "-DskipTests -DskipITs"
        maven-repo-server-id: github
        maven-repo-server-username: ${{ github.actor }}
        maven-repo-server-password: ${{ secrets.GITHUB_TOKEN }}
        maven-release-version-number: ${{ github.ref }}
      env:
        JAVA_HOME: /usr/lib/jvm/java-15-openjdk/
