name: CI

on:
  push:
    branches:
    - main
    - bugfix/**
    - feature/**
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:

jobs:

  foo:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.matrixgen.outputs.images }}
    steps:

      - uses: actions/checkout@v4

      - name: Generate Image Test Matrix
        id: matrixgen
        run: |
          echo "images=$(
            first=true
            echo -n '['
            for i in $(grep -r --include="docker-compose.yml" -Pho 'image: \K(.+)$' | tr -d "\"'" | sort | uniq)
            do
              if $first
              then
                first=false
              else
                echo -n ","
              fi
              echo -n '"'$i'"'
            done
            echo ']')" >> "$GITHUB_OUTPUT"


  bar:
    runs-on: ubuntu-latest
    needs: foo
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.foo.outputs.images) }}
    steps:
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          format: sarif
          output: trivy-results.sarif
          severity: 'CRITICAL,HIGH'
          timeout: '15m0s'

      - name: Upload Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 21

    - name: Cache Local Maven Repo
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
        key: maven-repo

    - name: Add GitHub Server Credentials to Maven settings.xml
      uses: s4u/maven-settings-action@v3.1.0
      with:
        servers: '[{"id": "github-umessen", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

    - name: Build with Maven
      run: mvn -B verify --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.actor }}

  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create artifacts
      run: echo foo > foo; zip foo.zip foo

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Child - v${{ steps.prep.outputs.version }}"
        files: "*.zip"
        fail_on_unmatched_files: true
