name: CI

on:
  push:
    branches:
    - main
    - bugfix/**
    - feature/**
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:

jobs:

  foo:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.matrixgen.outputs.images }}
    steps:

      - uses: actions/checkout@v3

      - name: Generate Image Test Matrix
        id: matrixgen
        run: |
          echo "images=$(
            first=true
            echo -n '['
            for i in $(grep -r --include="docker-compose.yml" -Pho 'image: \K(.+)$' | tr -d "\"'" | sort | uniq)
            do
              if $first
              then
                first=false
              else
                echo -n ","
              fi
              echo -n '"'$i'"'
            done
            echo ']')" >> "$GITHUB_OUTPUT"

  bar:
    runs-on: ubuntu-latest
    needs: foo
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.foo.outputs.images) }}
    steps:
      - name: Scan Image ${{ matrix.image }}
        run: echo "Scanning image ${{ matrix.image }}"

